services:
  - type: web
    name: bg-remover-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --timeout 300 --workers 1 --threads 1 --max-requests 10 --max-requests-jitter 5
    plan: free
    envVars:
      - key: U2NET_HOME
        value: /tmp/.u2net